### ISSUE TITLE
vm crashed on ConnectToPort

### ISSUE THREAD

**Issue by aoxn** [Code-Hex/vz#24]
``` log

podman login: I0114 20:50:46.031453   40317 proxy_darwin.go:17] [host] prepare to connect to vm port=2375
I0114 20:50:46.033429   40317 proxy_darwin.go:26] [host]connect to vm success 2375
I0114 20:50:54.184381   40317 publish.go:138] stream copy finish: c00079c000 -> c00079c010, 179 bytes copied
I0114 20:50:54.184478   40317 proxy_darwin.go:34] [host] stream copy finished [2375]
E0114 20:50:54.184649   40317 publish.go:133] stream copy: 486 bytes copied, read c7gn39lmk1u9qvafqfjg: file already closed
I0114 20:50:54.184686   40317 publish.go:148] close conn
I0114 20:50:54.184700   40317 publish.go:138] stream copy finish: c000522000 -> c000522010, 486 bytes copied
I0114 20:50:54.184729   40317 publish.go:148] close conn
I0114 20:50:57.409293   40317 proxy_darwin.go:17] [host] prepare to connect to vm port=2375
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3eaddc3d8248 pc=0x7ff80ee4f05d]

runtime stack:
runtime.throw({0x601d861, 0x3d0e336f5ff80060})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 62 [syscall]:
runtime.cgocall(0x59c6a70, 0xc000735e10)
	/usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc000735de8 sp=0xc000735db0 pc=0x400739c
github.com/aoxn/ovm/pkg/utils/vz._Cfunc_VZVirtioSocketDevice_connectToPort(0x600002908230, 0x600002c08880, 0x947, 0x6000002092c0)
	_cgo_gotypes.go:146 +0x45 fp=0xc000735e10 sp=0xc000735de8 pc=0x59159a5
github.com/aoxn/ovm/pkg/utils/vz.(*VirtioSocketDevice).ConnectToPort.func1(0xc000465380, 0x14, 0xc000465380)
	/Users/aoxn/vaoxn/code/ovm/pkg/utils/vz/socket.go:127 +0x85 fp=0xc000735e60 sp=0xc000735e10 pc=0x591ac85
github.com/aoxn/ovm/pkg/utils/vz.(*VirtioSocketDevice).ConnectToPort(0xc0005b3580, 0x1, 0xc00078e000)
	/Users/aoxn/vaoxn/code/ovm/pkg/utils/vz/socket.go:127 +0xc5 fp=0xc000735eb0 sp=0xc000735e60 pc=0x591aba5
github.com/aoxn/ovm/cmd/ovm/vm.NewVSockProxy.func1({0x630af18, 0xc000128020})
	/Users/aoxn/vaoxn/code/ovm/cmd/ovm/vm/proxy_darwin.go:40 +0x178 fp=0xc000735f50 sp=0xc000735eb0 pc=0x5921c58
github.com/aoxn/ovm/cmd/ovm/vm.(*Publish).Listen.func1({0x630af18, 0xc000128020})
	/Users/aoxn/vaoxn/code/ovm/cmd/ovm/vm/publish.go:122 +0x2f fp=0xc000735fc0 sp=0xc000735f50 pc=0x5922f4f
github.com/aoxn/ovm/cmd/ovm/vm.(*Publish).Listen·dwrap·9()
	/Users/aoxn/vaoxn/code/ovm/cmd/ovm/vm/publish.go:126 +0x31 fp=0xc000735fe0 sp=0xc000735fc0 pc=0x5922ef1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000735fe8 sp=0xc000735fe0 pc=0x4069541
created by github.com/aoxn/ovm/cmd/ovm/vm.(*Publish).Listen
	/Users/aoxn/vaoxn/code/ovm/cmd/ovm/vm/publish.go:121 +0x505
```

**Comment by aoxn** [comment]
remove runtime.SetFinalizer would avoid crash.  dont know why. 

``` go

func newVirtioSocketDevice(ptr, dispatchQueue unsafe.Pointer) *VirtioSocketDevice {
	id := xid.New().String()
	socketDevice := &VirtioSocketDevice{
		id:            id,
		dispatchQueue: dispatchQueue,
		pointer: pointer{
			ptr: ptr,
		},
	}
	connectionHandlers[id] = func(*VirtioSocketConnection, error) {}

	//runtime.SetFinalizer(socketDevice, func(self *VirtioSocketDevice) {
	//	self.Release()
	//})
	return socketDevice
}
```

**Comment by Code-Hex** [comment]
dup https://github.com/Code-Hex/vz/issues/13
